name: CI

on: [push, pull_request]

jobs:
  build:
    name: test_release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: NPM install
      run: npm install
    - name: Build
      run: npm run build

    - name: Package
      run: |
        mv index-macos dprint-plugin-prettier
        zip -r dprint-plugin-prettier-x86_64-apple-darwin.zip dprint-plugin-prettier
        rm dprint-plugin-prettier
        mv index-linux dprint-plugin-prettier
        zip -r dprint-plugin-prettier-x86_64-unknown-linux-gnu.zip dprint-plugin-prettier
        mv index-win.exe dprint-plugin-prettier.exe
        zip -r dprint-plugin-prettier-x86_64-pc-windows-msvc.zip dprint-plugin-prettier

    - name: Create plugin file
      run: node scripts/createPluginFile.js

    - name: Get tag version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag_version
      run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Get plugin file checksum
      if: startsWith(github.ref, 'refs/tags/')
      id: get_plugin_file_checksum
      run: echo "::set-output name=CHECKSUM::$(shasum -a 256 prettier.plugin | awk '{print $1}')"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dprint-plugin-prettier-x86_64-apple-darwin.zip
          dprint-plugin-prettier-x86_64-unknown-linux-gnu.zip
          dprint-plugin-prettier-x86_64-pc-windows-msvc.zip
          prettier.plugin
        body: |
          ## Install

          Add the following entry to your `plugins` array in *.dprintrc.json*:

          ```jsonc
          {
            // etc...
            "plugins": [
              "https://plugins.dprint.dev/prettier-${{ steps.get_tag_version.outputs.TAG_VERSION }}.plugin@${{ steps.get_plugin_file_checksum.CHECKSUM }}"
            ]
          }
          ```
        draft: true
